name: Release
run-name: "Release Version"
on:
  push:
    branches:
      - main
  # pull_request:
  #   types: closed
  #   branches:
  #     - main
jobs:
  Run-Python-Code:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'running someAction'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Textfile
        run: python someAction.py
      - name: Archive text artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-output
          path: |
            output
  Release-Artifact:
    runs-on: ubuntu-latest
    needs: [Run-Python-Code]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Download artifact"
        uses: actions/download-artifact@v4
        with:
          name: my-output
      - name: "Tag Version"
        uses: christophebedard/tag-version-commit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_tag_prefix: "v"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "my-output.zip"
          body: "here is some text"
          tag: "test01"
